### PR TITLE
Cmd sed

### PR DESCRIPTION
**Pull request by AgnieszkaBylica**

### CODE REVIEW

**Comment by Ernold11** [comment]
Check List
----------
* [ ]  CI is passed
* [ ]  master is merged into current branch
* [ ]  public methods should be at the top of class, protected at bottom  
       example: `on_new_line()` is public, `_parse()` is protected
* [ ]  Name of methods should tell what its doing, not how are doing  
       example: `_parse_re_via_dev_proto_metric()` -> `_parse_via_dev_proto_metric()`
* [ ]  All parsing lines (on_new_line) should be covered by unit tests
* [ ]  Be sure that  COMMAND_OUTPUT_* / COMMAND_KWARGS_* / COMMAND_RESULT_* cover all parsing lines
* [ ]  Parsed line example, parsing regexp, parsing method should be next to each other
* [ ]  Using named groups inside regexp (like `r"^\s*(?P<ADDRESS>\S+)\s+via\s+(?P<VIA>\S+)”`) is preferred
* [ ]  Longer regexp are before shorter regexp
* [ ]  Resources for pytest should be declared as `@pytest.fixture` or `@pytest.yield_fixture`

**Comment by Ernold11** [comment]
Please fix(look at check list and below):
- rename `parse` into `parse_line`,
- `cmd = cmd + " -e '{}'".format(script)` why that way? `cmd = "{} -e {}".format(cmd, script) is simple - please fix all occurency,
- don't use python specific name as your local variable e.g. `file`,
- I don't understand sense of method `_is_input_file` and `_is_script`. `input_files` and `script_files` is list of string so check if it is empty is simple,

**Comment by marcin-usielski** [comment]
This command does not work on line transferred in more than one package (real device, not test with the whole output in one package).
if is_full_line:
....
elif not self.done() and not self._result_set:
            self.set_result({})

**Comment by AgnieszkaBylica** [comment]
I've deleted this lines "elif not self.done() and not self._result_set: self.set_result({})" and now when command prints no result, result is empty list. Does it work now for line transferred in more than one package?

**Comment by marcin-usielski** [comment]
Please use only English in code and also in usage examples:
"Aga
Ania
Andrzej
Antoni
jAblko
gruszkA"

**Comment by Ernold11** [comment]
You still have Polish word in command output - see your test file.

**Comment by AgnieszkaBylica** [comment]
I think I've deleted all polish words.

**Comment by marcin-usielski** [comment]
False comments  in __init__:
        self.options = options            # string
        self.scripts = scripts            # list of strings
        self.script_files = script_files  # list of strings
        self.input_files = input_files    # list of strings
        self.output_file = output_file    # string
That's not true. All of them can be also None (default values)

**Pull request merged**
