### PR TITLE
Test for commands documentation

### PR DESCRIPTION
**Pull request by emcek**
* Main tasks:
  * clean up
  * move to moler package
  * add unit tests

* Subtasks:
  * fix logger for RAW_DATA
  * handling unicode / ascii correctly by logger

### CODE REVIEW

**Comment by Ernold11** [comment]
Check List
----------
* [ ]  CI is passed
* [ ]  master is merged into current branch
* [ ]  public methods should be at the top of class, protected at bottom  
       example: `on_new_line()` is public, `_parse()` is protected
* [ ]  Name of methods should tell what its doing, not how are doing  
       example: `_parse_re_via_dev_proto_metric()` -> `_parse_via_dev_proto_metric()`
* [ ]  All parsing lines (on_new_line) should be covered by unit tests
* [ ]  Be sure that  COMMAND_OUTPUT_* / COMMAND_KWARGS_* / COMMAND_RESULT_* cover all parsing lines
* [ ]  Parsed line example, parsing regexp, parsing method should be next to each other
* [ ]  Using named groups inside regexp (like `r"^\s*(?P<ADDRESS>\S+)\s+via\s+(?P<VIA>\S+)”`) is preferred
* [ ]  Longer regexp are before shorter regexp
* [ ]  Resources for pytest should be declared as `@pytest.fixture` or `@pytest.yield_fixture`

**Comment by Ernold11** [comment]
Run for CLI doesn't work. 

When i pass argument:

- ```--cmd_filename=moler/cmd```

into cmds_doc.py script only return:

- `All processed commands have correct documentation`

But no process any files.

In method:

- ```def check_if_documentation_exists(path2cmds):```

script doesn't iterate in for loop:

- ```for moler_module, moler_class in _walk_moler_nonabstract_commands(path=path2cmds):```

I found that in method:

- ```def _walk_moler_python_files(path)```

after execute:

- ```path = join(__file__.partition('moler/util/cmds_doc.py')[0], path)```

atribute path value is:

- ```/home/ernold11/auto/github/util/cmds_doc.py/moler/cmd```

which is incorrect value.

Please fix this issue.

**Comment by Ernold11** [comment]
All work properly. Merge.

**Comment by emcek** [comment]
`cmds_doc.py` script is moved from `util` to `moler/util` directory to be part of package

**Pull request merged**
