### PR TITLE
Cmd useradd

### PR DESCRIPTION
**Pull request by AgnieszkaBylica**

### CODE REVIEW

**Comment by Ernold11** [comment]
Check List
----------
* [ ]  CI is passed
* [ ]  master is merged into current branch
* [ ]  public methods should be at the top of class, protected at bottom  
       example: `on_new_line()` is public, `_parse()` is protected
* [ ]  Name of methods should tell what its doing, not how are doing  
       example: `_parse_re_via_dev_proto_metric()` -> `_parse_via_dev_proto_metric()`
* [ ]  All parsing lines (on_new_line) should be covered by unit tests
* [ ]  Be sure that  COMMAND_OUTPUT_* / COMMAND_KWARGS_* / COMMAND_RESULT_* cover all parsing lines
* [ ]  Parsed line example, parsing regexp, parsing method should be next to each other
* [ ]  Using named groups inside regexp (like `r"^\s*(?P<ADDRESS>\S+)\s+via\s+(?P<VIA>\S+)”`) is preferred
* [ ]  Longer regexp are before shorter regexp
* [ ]  Resources for pytest should be declared as `@pytest.fixture` or `@pytest.yield_fixture`

**Comment by Ernold11** [comment]
Please fix(look at check list and below):
- `cmd = cmd + " {}".format(d_option)` why that way? `cmd = "{} {}".format(cmd, d_option) is simple - please fix all occurency,
- I don't understand why this line: `elif not self.done() and not self._result_set:` is elif for `if is_full_line`?
- in `def _command_error(self, line):` `if` and `elif` have the same body. Why not create list of regex and iterate over it?

**Comment by AgnieszkaBylica** [comment]
@Ernold11 
I think I've fixed everything. Is it alright now?

**Comment by Ernold11** [comment]
`_regex_compiled` should be class attribute not instance.

**Comment by AgnieszkaBylica** [comment]
@Ernold11 
I've changed it. Is is ok?

**Comment by marcin-usielski** [comment]
Parameter defaults with default value False will be more readable.

**Comment by AgnieszkaBylica** [comment]
You're right. I've changed it.

**Pull request merged**
