### PR TITLE
Cmd hexdump

### PR DESCRIPTION
**Pull request by AdriannaPienkowska**

### CODE REVIEW

**Comment by Ernold11** [comment]
Check List
----------
* [ ]  CI is passed
* [ ]  master is merged into current branch
* [ ]  public methods should be at the top of class, protected at bottom  
       example: `on_new_line()` is public, `_parse()` is protected
* [ ]  Name of methods should tell what its doing, not how are doing  
       example: `_parse_re_via_dev_proto_metric()` -> `_parse_via_dev_proto_metric()`
* [ ]  All parsing lines (on_new_line) should be covered by unit tests
* [ ]  Be sure that  COMMAND_OUTPUT_* / COMMAND_KWARGS_* / COMMAND_RESULT_* cover all parsing lines
* [ ]  Parsed line example, parsing regexp, parsing method should be next to each other
* [ ]  Using named groups inside regexp (like `r"^\s*(?P<ADDRESS>\S+)\s+via\s+(?P<VIA>\S+)”`) is preferred
* [ ]  Longer regexp are before shorter regexp
* [ ]  Resources for pytest should be declared as `@pytest.fixture` or `@pytest.yield_fixture`
* [ ]  There are no sensitive data (company specific) like: IP addr, passwords, commands, tools etc

**Comment by Ernold11** [comment]
Please fix your command(look at checklist and below):

- rename `_parse` into `_parse_line`,
- `cmd = cmd + " {}".format(file)` why that way? `cmd = "{} {}".format(cmd, file) is simple - please fix all occurency,
- don't use python specific name as your local variable e.g. `file`,
- I don't understand sense of method `_is_file`  `self.files` is list of string so check if it is empty is simple,

**Comment by marcin-usielski** [comment]
Maybe:
_parse -> _parse_line -> _parse_hex_line?
And what do you think to put every hex into separate item of list? Much easier to write script using hexdump.

**Comment by AdriannaPienkowska** [comment]
@marcin-usielski so the output will look like, e.g:
'RESULT': ['00000', '101', '147'] ?

**Comment by marcin-usielski** [comment]
@AdriannaPienkowska 
Exactly.

**Comment by AdriannaPienkowska** [comment]
@Ernold11 _is_file() (I have renamed it to _is_file_name()) is there to make sure file names are not all empty or whitespace names. Hexdump won't rise error at such occurence to be handled by _command_failure() but will wait for standard input data. I was told it is not the desirable behaviour.

**Comment by Ernold11** [comment]
Ok @AdriannaPienkowska. So lets do other necessary fixes first but I don't like how this function look like. We must find a better way to check this condition.

**Comment by marcin-usielski** [comment]
Is that a real problem? In such case timeout occurs, ctrl+c will be sent by base class and we have available console to execute next commands and info to script (exception).

**Comment by AdriannaPienkowska** [comment]
I will push the changes I had made in it and will see if it will look better. Ok?

**Comment by marcin-usielski** [comment]
Please note the first numbers in every line of output are not values of files, they are address/offset in file. I don't think they should be mixed together in one list. So maybe skip the offset ?

**Comment by Ernold11** [comment]
I think @marcin-usielski is right. I also think that we can skip offset.

**Comment by AdriannaPienkowska** [comment]
Ok, but please notice if there are more files as arguments given then if I strip them of the offset it will be imposible to distinquish which data comes from which file. I was wondering if I should put the results of each file in separate lists but that also may cause some problems. So should I strip each file of its offset, remove only first and leave the others or do something else?

**Comment by Ernold11** [comment]
So @AdriannaPienkowska first write test for multiple files as input files. Maybe ret should look like:
```
ret = {
   'file_name': {
      'offset': ['data1', 'data2', ..., 'datan']
   },
}
```
What do you think @marcin-usielski ?

**Comment by marcin-usielski** [comment]
Real output from hexdump does not show which bytes are from which file:
```
ute@debdev:~/tmp$ hexdump  a.txt b.txt
0000000 6261 0a63 6361 0a64
0000008
> ute@debdev:~/tmp$
```
So there is no reason  to care in Moler output.

**Comment by Ernold11** [comment]
Ok so lets just ignore offset and that will be best solution.

**Comment by AdriannaPienkowska** [comment]
Ok. Done.

**Comment by marcin-usielski** [comment]
That's OK

**Pull request merged**
